matrix:
  include:
  - stage: Tox Test
    name: "Unittesting"
    language: python
    python:
    - "3.6"
    install: pip install tox-travis
    script: tox
  - stage: Cypress Test
    name: "Cypress Testing"
    language: node_js
    node_js:
      - 10
    cache:
      npm: true
      directories:
        - ~/.npm
        - ~/.cache
        - node_modules
      node_js:
        - '8'
    install:
      - cd src/main/vue
      - npm ci
    script:
      - mv cypress/integration/testing.spec.js /
      - npm install cypress --save
      - rm -r cypress/intgeration/*
      - mv testing.spec.js cypress/integration
      - npm run cy:run