matrix:
  include:
  - stage: Tox Test
    name: "Unittesting"
    language: python
    python:
    - "3.6"
    install: pip install tox-travis
    script: tox
  - stage: Cypress Test
    name: "Cypress Testing"
    language: node_js
    node_js:
      - 10
    cache:
      npm: true
      directories:
        - ~/.cache
    before_script: cd src/main/vue
    script:
      - npm ci
      - cypress run --record